import type { Metadata } from 'next';
import { Krona_One } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const kronaOne = Krona_One({
    subsets: ['latin'],
    weight: '400',
    variable: '--font-krona-one',
});
const messinaSans = localFont({
    src: [
        {
            path: './MessinaSans-Regular.woff2',
            weight: 'normal',
        },
        {
            path: './MessinaSans-Bold.woff2',
            weight: 'bold',
        },
        {
          path: './MessinaSerif-SemiBoldItalic.woff2',
          style: 'italic',
          weight: 'normal'
      
        }
    ],
    variable: '--font-messina-sans',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${kronaOne.variable} ${messinaSans.variable}`}>
            <body>{children}</body>
        </html>
    );
}
